from . import res_partner
from . import labour_category
from . import labour_photo
from . import labour_sheet
from . import weekly_bill
from . import wage_slip
from . import res_config_settings
from . import daily_wage
from . import daily_bill
